// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: sink/sink.proto

package sinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompletionMode defines the point at which a mutating RPC returns success.
type CompletionMode int32

const (
	CompletionMode_COMPLETION_MODE_UNSPECIFIED CompletionMode = 0
	// Wait until the storage adapter has applied each operation.
	CompletionMode_COMPLETION_MODE_WAIT_UNTIL_APPLIED CompletionMode = 1
	// Return after a durable asynchronous queue has accepted each operation.
	// Acceptance does not mean that the storage adapter has applied it.
	CompletionMode_COMPLETION_MODE_RETURN_AFTER_ACCEPTED CompletionMode = 2
	// Wait until the storage adapter has applied each operation and made the
	// result visible to subsequent reads. Search adapters use refresh=wait_for.
	CompletionMode_COMPLETION_MODE_WAIT_UNTIL_VISIBLE CompletionMode = 3
)

// Enum value maps for CompletionMode.
var (
	CompletionMode_name = map[int32]string{
		0: "COMPLETION_MODE_UNSPECIFIED",
		1: "COMPLETION_MODE_WAIT_UNTIL_APPLIED",
		2: "COMPLETION_MODE_RETURN_AFTER_ACCEPTED",
		3: "COMPLETION_MODE_WAIT_UNTIL_VISIBLE",
	}
	CompletionMode_value = map[string]int32{
		"COMPLETION_MODE_UNSPECIFIED":           0,
		"COMPLETION_MODE_WAIT_UNTIL_APPLIED":    1,
		"COMPLETION_MODE_RETURN_AFTER_ACCEPTED": 2,
		"COMPLETION_MODE_WAIT_UNTIL_VISIBLE":    3,
	}
)

func (x CompletionMode) Enum() *CompletionMode {
	p := new(CompletionMode)
	*p = x
	return p
}

func (x CompletionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompletionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[0].Descriptor()
}

func (CompletionMode) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[0]
}

func (x CompletionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompletionMode.Descriptor instead.
func (CompletionMode) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{0}
}

type ReadStatus int32

const (
	ReadStatus_READ_STATUS_UNSPECIFIED ReadStatus = 0
	ReadStatus_READ_STATUS_FOUND       ReadStatus = 1
	ReadStatus_READ_STATUS_NOT_FOUND   ReadStatus = 2
	ReadStatus_READ_STATUS_FAILED      ReadStatus = 3
)

// Enum value maps for ReadStatus.
var (
	ReadStatus_name = map[int32]string{
		0: "READ_STATUS_UNSPECIFIED",
		1: "READ_STATUS_FOUND",
		2: "READ_STATUS_NOT_FOUND",
		3: "READ_STATUS_FAILED",
	}
	ReadStatus_value = map[string]int32{
		"READ_STATUS_UNSPECIFIED": 0,
		"READ_STATUS_FOUND":       1,
		"READ_STATUS_NOT_FOUND":   2,
		"READ_STATUS_FAILED":      3,
	}
)

func (x ReadStatus) Enum() *ReadStatus {
	p := new(ReadStatus)
	*p = x
	return p
}

func (x ReadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[1].Descriptor()
}

func (ReadStatus) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[1]
}

func (x ReadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadStatus.Descriptor instead.
func (ReadStatus) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{1}
}

type WriteMode int32

const (
	WriteMode_WRITE_MODE_UNSPECIFIED WriteMode = 0
	WriteMode_WRITE_MODE_CREATE      WriteMode = 1
	WriteMode_WRITE_MODE_REPLACE     WriteMode = 2
	WriteMode_WRITE_MODE_UPSERT      WriteMode = 3
)

// Enum value maps for WriteMode.
var (
	WriteMode_name = map[int32]string{
		0: "WRITE_MODE_UNSPECIFIED",
		1: "WRITE_MODE_CREATE",
		2: "WRITE_MODE_REPLACE",
		3: "WRITE_MODE_UPSERT",
	}
	WriteMode_value = map[string]int32{
		"WRITE_MODE_UNSPECIFIED": 0,
		"WRITE_MODE_CREATE":      1,
		"WRITE_MODE_REPLACE":     2,
		"WRITE_MODE_UPSERT":      3,
	}
)

func (x WriteMode) Enum() *WriteMode {
	p := new(WriteMode)
	*p = x
	return p
}

func (x WriteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[2].Descriptor()
}

func (WriteMode) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[2]
}

func (x WriteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteMode.Descriptor instead.
func (WriteMode) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{2}
}

type MissingDocumentMode int32

const (
	MissingDocumentMode_MISSING_DOCUMENT_MODE_UNSPECIFIED MissingDocumentMode = 0
	MissingDocumentMode_MISSING_DOCUMENT_MODE_FAIL        MissingDocumentMode = 1
	MissingDocumentMode_MISSING_DOCUMENT_MODE_CREATE      MissingDocumentMode = 2
)

// Enum value maps for MissingDocumentMode.
var (
	MissingDocumentMode_name = map[int32]string{
		0: "MISSING_DOCUMENT_MODE_UNSPECIFIED",
		1: "MISSING_DOCUMENT_MODE_FAIL",
		2: "MISSING_DOCUMENT_MODE_CREATE",
	}
	MissingDocumentMode_value = map[string]int32{
		"MISSING_DOCUMENT_MODE_UNSPECIFIED": 0,
		"MISSING_DOCUMENT_MODE_FAIL":        1,
		"MISSING_DOCUMENT_MODE_CREATE":      2,
	}
)

func (x MissingDocumentMode) Enum() *MissingDocumentMode {
	p := new(MissingDocumentMode)
	*p = x
	return p
}

func (x MissingDocumentMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissingDocumentMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[3].Descriptor()
}

func (MissingDocumentMode) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[3]
}

func (x MissingDocumentMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MissingDocumentMode.Descriptor instead.
func (MissingDocumentMode) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{3}
}

type WriteStatus int32

const (
	WriteStatus_WRITE_STATUS_UNSPECIFIED WriteStatus = 0
	// The asynchronous queue accepted the operation durably.
	WriteStatus_WRITE_STATUS_ACCEPTED WriteStatus = 1
	// The storage adapter applied the operation.
	WriteStatus_WRITE_STATUS_APPLIED WriteStatus = 2
	// A CREATE, REPLACE, or adapter-level revision condition did not match.
	WriteStatus_WRITE_STATUS_PRECONDITION_FAILED WriteStatus = 3
	WriteStatus_WRITE_STATUS_FAILED              WriteStatus = 4
)

// Enum value maps for WriteStatus.
var (
	WriteStatus_name = map[int32]string{
		0: "WRITE_STATUS_UNSPECIFIED",
		1: "WRITE_STATUS_ACCEPTED",
		2: "WRITE_STATUS_APPLIED",
		3: "WRITE_STATUS_PRECONDITION_FAILED",
		4: "WRITE_STATUS_FAILED",
	}
	WriteStatus_value = map[string]int32{
		"WRITE_STATUS_UNSPECIFIED":         0,
		"WRITE_STATUS_ACCEPTED":            1,
		"WRITE_STATUS_APPLIED":             2,
		"WRITE_STATUS_PRECONDITION_FAILED": 3,
		"WRITE_STATUS_FAILED":              4,
	}
)

func (x WriteStatus) Enum() *WriteStatus {
	p := new(WriteStatus)
	*p = x
	return p
}

func (x WriteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[4].Descriptor()
}

func (WriteStatus) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[4]
}

func (x WriteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteStatus.Descriptor instead.
func (WriteStatus) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{4}
}

type DeleteStatus int32

const (
	DeleteStatus_DELETE_STATUS_UNSPECIFIED DeleteStatus = 0
	DeleteStatus_DELETE_STATUS_ACCEPTED    DeleteStatus = 1
	DeleteStatus_DELETE_STATUS_APPLIED     DeleteStatus = 2
	DeleteStatus_DELETE_STATUS_FAILED      DeleteStatus = 3
)

// Enum value maps for DeleteStatus.
var (
	DeleteStatus_name = map[int32]string{
		0: "DELETE_STATUS_UNSPECIFIED",
		1: "DELETE_STATUS_ACCEPTED",
		2: "DELETE_STATUS_APPLIED",
		3: "DELETE_STATUS_FAILED",
	}
	DeleteStatus_value = map[string]int32{
		"DELETE_STATUS_UNSPECIFIED": 0,
		"DELETE_STATUS_ACCEPTED":    1,
		"DELETE_STATUS_APPLIED":     2,
		"DELETE_STATUS_FAILED":      3,
	}
)

func (x DeleteStatus) Enum() *DeleteStatus {
	p := new(DeleteStatus)
	*p = x
	return p
}

func (x DeleteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[5].Descriptor()
}

func (DeleteStatus) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[5]
}

func (x DeleteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteStatus.Descriptor instead.
func (DeleteStatus) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{5}
}

type FailureCode int32

const (
	FailureCode_FAILURE_CODE_UNSPECIFIED         FailureCode = 0
	FailureCode_FAILURE_CODE_INVALID_ARGUMENT    FailureCode = 1
	FailureCode_FAILURE_CODE_PRECONDITION_FAILED FailureCode = 2
	FailureCode_FAILURE_CODE_NOT_FOUND           FailureCode = 3
	FailureCode_FAILURE_CODE_CONFLICT            FailureCode = 4
	FailureCode_FAILURE_CODE_RESOURCE_EXHAUSTED  FailureCode = 5
	FailureCode_FAILURE_CODE_UNAVAILABLE         FailureCode = 6
	FailureCode_FAILURE_CODE_DEADLINE_EXCEEDED   FailureCode = 7
	FailureCode_FAILURE_CODE_INTERNAL            FailureCode = 8
)

// Enum value maps for FailureCode.
var (
	FailureCode_name = map[int32]string{
		0: "FAILURE_CODE_UNSPECIFIED",
		1: "FAILURE_CODE_INVALID_ARGUMENT",
		2: "FAILURE_CODE_PRECONDITION_FAILED",
		3: "FAILURE_CODE_NOT_FOUND",
		4: "FAILURE_CODE_CONFLICT",
		5: "FAILURE_CODE_RESOURCE_EXHAUSTED",
		6: "FAILURE_CODE_UNAVAILABLE",
		7: "FAILURE_CODE_DEADLINE_EXCEEDED",
		8: "FAILURE_CODE_INTERNAL",
	}
	FailureCode_value = map[string]int32{
		"FAILURE_CODE_UNSPECIFIED":         0,
		"FAILURE_CODE_INVALID_ARGUMENT":    1,
		"FAILURE_CODE_PRECONDITION_FAILED": 2,
		"FAILURE_CODE_NOT_FOUND":           3,
		"FAILURE_CODE_CONFLICT":            4,
		"FAILURE_CODE_RESOURCE_EXHAUSTED":  5,
		"FAILURE_CODE_UNAVAILABLE":         6,
		"FAILURE_CODE_DEADLINE_EXCEEDED":   7,
		"FAILURE_CODE_INTERNAL":            8,
	}
)

func (x FailureCode) Enum() *FailureCode {
	p := new(FailureCode)
	*p = x
	return p
}

func (x FailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[6].Descriptor()
}

func (FailureCode) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[6]
}

func (x FailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureCode.Descriptor instead.
func (FailureCode) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{6}
}

// RecordAddress identifies a record without exposing a physical database,
// collection, table, or primary-key field name.
type RecordAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Dataset       string                 `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Key           *RecordKey             `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAddress) Reset() {
	*x = RecordAddress{}
	mi := &file_sink_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAddress) ProtoMessage() {}

func (x *RecordAddress) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAddress.ProtoReflect.Descriptor instead.
func (*RecordAddress) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{0}
}

func (x *RecordAddress) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *RecordAddress) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RecordAddress) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *RecordAddress) GetKey() *RecordKey {
	if x != nil {
		return x.Key
	}
	return nil
}

// RecordKey is encoded deterministically so it can also be used for routing.
// Opaque keys preserve storage-specific legacy key types without teaching the
// Sink core how to interpret them.
type RecordKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RecordKey_StringValue
	//	*RecordKey_Int64Value
	//	*RecordKey_BytesValue
	//	*RecordKey_OpaqueValue
	Kind          isRecordKey_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordKey) Reset() {
	*x = RecordKey{}
	mi := &file_sink_sink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordKey) ProtoMessage() {}

func (x *RecordKey) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordKey.ProtoReflect.Descriptor instead.
func (*RecordKey) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{1}
}

func (x *RecordKey) GetKind() isRecordKey_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RecordKey) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*RecordKey_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *RecordKey) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*RecordKey_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *RecordKey) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*RecordKey_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *RecordKey) GetOpaqueValue() *OpaqueValue {
	if x != nil {
		if x, ok := x.Kind.(*RecordKey_OpaqueValue); ok {
			return x.OpaqueValue
		}
	}
	return nil
}

type isRecordKey_Kind interface {
	isRecordKey_Kind()
}

type RecordKey_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type RecordKey_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type RecordKey_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,3,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type RecordKey_OpaqueValue struct {
	OpaqueValue *OpaqueValue `protobuf:"bytes,4,opt,name=opaque_value,json=opaqueValue,proto3,oneof"`
}

func (*RecordKey_StringValue) isRecordKey_Kind() {}

func (*RecordKey_Int64Value) isRecordKey_Kind() {}

func (*RecordKey_BytesValue) isRecordKey_Kind() {}

func (*RecordKey_OpaqueValue) isRecordKey_Kind() {}

type OpaqueValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpaqueValue) Reset() {
	*x = OpaqueValue{}
	mi := &file_sink_sink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueValue) ProtoMessage() {}

func (x *OpaqueValue) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpaqueValue.ProtoReflect.Descriptor instead.
func (*OpaqueValue) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{2}
}

func (x *OpaqueValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OpaqueValue) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Document contains a JSON-encoded user object. Storage-specific encodings are
// private implementation details of storage adapters.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Json  []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	// RFC 6901 JSON Pointers identifying strings that originated as typed
	// date-time values. Adapters that support a native date-time type may use
	// this metadata without changing the JSON representation.
	DateTimePaths []string `protobuf:"bytes,2,rep,name=date_time_paths,json=dateTimePaths,proto3" json:"date_time_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_sink_sink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{3}
}

func (x *Document) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *Document) GetDateTimePaths() []string {
	if x != nil {
		return x.DateTimePaths
	}
	return nil
}

// RevisionToken is interpreted only by the selected storage adapter.
type RevisionToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionToken) Reset() {
	*x = RevisionToken{}
	mi := &file_sink_sink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionToken) ProtoMessage() {}

func (x *RevisionToken) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionToken.ProtoReflect.Descriptor instead.
func (*RevisionToken) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{4}
}

func (x *RevisionToken) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*ReadOperation       `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_sink_sink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRequest) GetOperations() []*ReadOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ReadOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *RecordAddress         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOperation) Reset() {
	*x = ReadOperation{}
	mi := &file_sink_sink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOperation) ProtoMessage() {}

func (x *ReadOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOperation.ProtoReflect.Descriptor instead.
func (*ReadOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{6}
}

func (x *ReadOperation) GetAddress() *RecordAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results are returned in request order. operation_index is included to make
	// correlation explicit when an implementation executes records in parallel.
	Results       []*ReadResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_sink_sink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{7}
}

func (x *ReadResponse) GetResults() []*ReadResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReadResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationIndex uint32                 `protobuf:"varint,1,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	Status         ReadStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=sink.v1.ReadStatus" json:"status,omitempty"`
	Document       *Document              `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	Revision       *RevisionToken         `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Failure        *Failure               `protobuf:"bytes,5,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadResult) Reset() {
	*x = ReadResult{}
	mi := &file_sink_sink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResult) ProtoMessage() {}

func (x *ReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResult.ProtoReflect.Descriptor instead.
func (*ReadResult) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{8}
}

func (x *ReadResult) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *ReadResult) GetStatus() ReadStatus {
	if x != nil {
		return x.Status
	}
	return ReadStatus_READ_STATUS_UNSPECIFIED
}

func (x *ReadResult) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ReadResult) GetRevision() *RevisionToken {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *ReadResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type WriteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompletionMode CompletionMode         `protobuf:"varint,1,opt,name=completion_mode,json=completionMode,proto3,enum=sink.v1.CompletionMode" json:"completion_mode,omitempty"`
	// Operations for the same address are executed in request order. Operations
	// for different addresses may execute concurrently.
	Operations []*WriteOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// Programs can be declared once and referenced by digest from multiple merge
	// operations, avoiding repeated Lua source bytes in a synchronous batch.
	LuaPrograms   []*LuaProgram `protobuf:"bytes,3,rep,name=lua_programs,json=luaPrograms,proto3" json:"lua_programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_sink_sink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{9}
}

func (x *WriteRequest) GetCompletionMode() CompletionMode {
	if x != nil {
		return x.CompletionMode
	}
	return CompletionMode_COMPLETION_MODE_UNSPECIFIED
}

func (x *WriteRequest) GetOperations() []*WriteOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *WriteRequest) GetLuaPrograms() []*LuaProgram {
	if x != nil {
		return x.LuaPrograms
	}
	return nil
}

type WriteOperation struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address *RecordAddress         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*WriteOperation_Put
	//	*WriteOperation_Merge
	Action        isWriteOperation_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOperation) Reset() {
	*x = WriteOperation{}
	mi := &file_sink_sink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOperation) ProtoMessage() {}

func (x *WriteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOperation.ProtoReflect.Descriptor instead.
func (*WriteOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{10}
}

func (x *WriteOperation) GetAddress() *RecordAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *WriteOperation) GetAction() isWriteOperation_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *WriteOperation) GetPut() *PutOperation {
	if x != nil {
		if x, ok := x.Action.(*WriteOperation_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *WriteOperation) GetMerge() *MergeOperation {
	if x != nil {
		if x, ok := x.Action.(*WriteOperation_Merge); ok {
			return x.Merge
		}
	}
	return nil
}

type isWriteOperation_Action interface {
	isWriteOperation_Action()
}

type WriteOperation_Put struct {
	Put *PutOperation `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type WriteOperation_Merge struct {
	Merge *MergeOperation `protobuf:"bytes,3,opt,name=merge,proto3,oneof"`
}

func (*WriteOperation_Put) isWriteOperation_Action() {}

func (*WriteOperation_Merge) isWriteOperation_Action() {}

// PutOperation writes a complete user document without interpreting its fields.
type PutOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Mode          WriteMode              `protobuf:"varint,2,opt,name=mode,proto3,enum=sink.v1.WriteMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutOperation) Reset() {
	*x = PutOperation{}
	mi := &file_sink_sink_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOperation) ProtoMessage() {}

func (x *PutOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOperation.ProtoReflect.Descriptor instead.
func (*PutOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{11}
}

func (x *PutOperation) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *PutOperation) GetMode() WriteMode {
	if x != nil {
		return x.Mode
	}
	return WriteMode_WRITE_MODE_UNSPECIFIED
}

// MergeOperation carries the original merge intent. In asynchronous mode Sink
// expands any program reference before queueing the operation so the worker can
// merge against the document version it reads at execution time.
type MergeOperation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IncomingDocument    *Document              `protobuf:"bytes,1,opt,name=incoming_document,json=incomingDocument,proto3" json:"incoming_document,omitempty"`
	MissingDocumentMode MissingDocumentMode    `protobuf:"varint,2,opt,name=missing_document_mode,json=missingDocumentMode,proto3,enum=sink.v1.MissingDocumentMode" json:"missing_document_mode,omitempty"`
	LuaProgram          *LuaProgram            `protobuf:"bytes,3,opt,name=lua_program,json=luaProgram,proto3" json:"lua_program,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MergeOperation) Reset() {
	*x = MergeOperation{}
	mi := &file_sink_sink_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeOperation) ProtoMessage() {}

func (x *MergeOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeOperation.ProtoReflect.Descriptor instead.
func (*MergeOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{12}
}

func (x *MergeOperation) GetIncomingDocument() *Document {
	if x != nil {
		return x.IncomingDocument
	}
	return nil
}

func (x *MergeOperation) GetMissingDocumentMode() MissingDocumentMode {
	if x != nil {
		return x.MissingDocumentMode
	}
	return MissingDocumentMode_MISSING_DOCUMENT_MODE_UNSPECIFIED
}

func (x *MergeOperation) GetLuaProgram() *LuaProgram {
	if x != nil {
		return x.LuaProgram
	}
	return nil
}

// LuaProgram is self-contained so merge rules can be versioned and deployed
// with the calling application instead of being registered in Sink.
type LuaProgram struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source may be omitted from a merge operation when the matching full program
	// is present in WriteRequest.lua_programs. Workers always receive full source.
	Source []byte `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Optional SHA-256 digest. Sink verifies it when present and always uses the
	// computed digest as the compiled-program cache key.
	Sha256        []byte `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuaProgram) Reset() {
	*x = LuaProgram{}
	mi := &file_sink_sink_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuaProgram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuaProgram) ProtoMessage() {}

func (x *LuaProgram) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuaProgram.ProtoReflect.Descriptor instead.
func (*LuaProgram) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{13}
}

func (x *LuaProgram) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LuaProgram) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*WriteResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_sink_sink_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{14}
}

func (x *WriteResponse) GetResults() []*WriteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type WriteResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationIndex uint32                 `protobuf:"varint,1,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	Status         WriteStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=sink.v1.WriteStatus" json:"status,omitempty"`
	Revision       *RevisionToken         `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Failure        *Failure               `protobuf:"bytes,4,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteResult) Reset() {
	*x = WriteResult{}
	mi := &file_sink_sink_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResult) ProtoMessage() {}

func (x *WriteResult) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResult.ProtoReflect.Descriptor instead.
func (*WriteResult) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{15}
}

func (x *WriteResult) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *WriteResult) GetStatus() WriteStatus {
	if x != nil {
		return x.Status
	}
	return WriteStatus_WRITE_STATUS_UNSPECIFIED
}

func (x *WriteResult) GetRevision() *RevisionToken {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *WriteResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompletionMode CompletionMode         `protobuf:"varint,1,opt,name=completion_mode,json=completionMode,proto3,enum=sink.v1.CompletionMode" json:"completion_mode,omitempty"`
	// Deletes are hard deletes. Deleting an absent record is successful.
	Operations    []*DeleteOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_sink_sink_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteRequest) GetCompletionMode() CompletionMode {
	if x != nil {
		return x.CompletionMode
	}
	return CompletionMode_COMPLETION_MODE_UNSPECIFIED
}

func (x *DeleteRequest) GetOperations() []*DeleteOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type DeleteOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *RecordAddress         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOperation) Reset() {
	*x = DeleteOperation{}
	mi := &file_sink_sink_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOperation) ProtoMessage() {}

func (x *DeleteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOperation.ProtoReflect.Descriptor instead.
func (*DeleteOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteOperation) GetAddress() *RecordAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DeleteResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_sink_sink_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResponse) GetResults() []*DeleteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationIndex uint32                 `protobuf:"varint,1,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	Status         DeleteStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=sink.v1.DeleteStatus" json:"status,omitempty"`
	Failure        *Failure               `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	mi := &file_sink_sink_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteResult) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *DeleteResult) GetStatus() DeleteStatus {
	if x != nil {
		return x.Status
	}
	return DeleteStatus_DELETE_STATUS_UNSPECIFIED
}

func (x *DeleteResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          FailureCode            `protobuf:"varint,1,opt,name=code,proto3,enum=sink.v1.FailureCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_sink_sink_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{20}
}

func (x *Failure) GetCode() FailureCode {
	if x != nil {
		return x.Code
	}
	return FailureCode_FAILURE_CODE_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Failure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_sink_sink_proto protoreflect.FileDescriptor

const file_sink_sink_proto_rawDesc = "" +
	"\n" +
	"\x0fsink/sink.proto\x12\asink.v1\"\x83\x01\n" +
	"\rRecordAddress\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\adataset\x18\x03 \x01(\tR\adataset\x12$\n" +
	"\x03key\x18\x04 \x01(\v2\x12.sink.v1.RecordKeyR\x03key\"\xb9\x01\n" +
	"\tRecordKey\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12!\n" +
	"\vbytes_value\x18\x03 \x01(\fH\x00R\n" +
	"bytesValue\x129\n" +
	"\fopaque_value\x18\x04 \x01(\v2\x14.sink.v1.OpaqueValueH\x00R\vopaqueValueB\x06\n" +
	"\x04kind\"5\n" +
	"\vOpaqueValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"F\n" +
	"\bDocument\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\x12&\n" +
	"\x0fdate_time_paths\x18\x02 \x03(\tR\rdateTimePaths\"#\n" +
	"\rRevisionToken\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"E\n" +
	"\vReadRequest\x126\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x16.sink.v1.ReadOperationR\n" +
	"operations\"A\n" +
	"\rReadOperation\x120\n" +
	"\aaddress\x18\x01 \x01(\v2\x16.sink.v1.RecordAddressR\aaddress\"=\n" +
	"\fReadResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.sink.v1.ReadResultR\aresults\"\xf1\x01\n" +
	"\n" +
	"ReadResult\x12'\n" +
	"\x0foperation_index\x18\x01 \x01(\rR\x0eoperationIndex\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.sink.v1.ReadStatusR\x06status\x12-\n" +
	"\bdocument\x18\x03 \x01(\v2\x11.sink.v1.DocumentR\bdocument\x122\n" +
	"\brevision\x18\x04 \x01(\v2\x16.sink.v1.RevisionTokenR\brevision\x12*\n" +
	"\afailure\x18\x05 \x01(\v2\x10.sink.v1.FailureR\afailure\"\xc1\x01\n" +
	"\fWriteRequest\x12@\n" +
	"\x0fcompletion_mode\x18\x01 \x01(\x0e2\x17.sink.v1.CompletionModeR\x0ecompletionMode\x127\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x17.sink.v1.WriteOperationR\n" +
	"operations\x126\n" +
	"\flua_programs\x18\x03 \x03(\v2\x13.sink.v1.LuaProgramR\vluaPrograms\"\xa8\x01\n" +
	"\x0eWriteOperation\x120\n" +
	"\aaddress\x18\x01 \x01(\v2\x16.sink.v1.RecordAddressR\aaddress\x12)\n" +
	"\x03put\x18\x02 \x01(\v2\x15.sink.v1.PutOperationH\x00R\x03put\x12/\n" +
	"\x05merge\x18\x03 \x01(\v2\x17.sink.v1.MergeOperationH\x00R\x05mergeB\b\n" +
	"\x06action\"e\n" +
	"\fPutOperation\x12-\n" +
	"\bdocument\x18\x01 \x01(\v2\x11.sink.v1.DocumentR\bdocument\x12&\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x12.sink.v1.WriteModeR\x04mode\"\xd8\x01\n" +
	"\x0eMergeOperation\x12>\n" +
	"\x11incoming_document\x18\x01 \x01(\v2\x11.sink.v1.DocumentR\x10incomingDocument\x12P\n" +
	"\x15missing_document_mode\x18\x02 \x01(\x0e2\x1c.sink.v1.MissingDocumentModeR\x13missingDocumentMode\x124\n" +
	"\vlua_program\x18\x03 \x01(\v2\x13.sink.v1.LuaProgramR\n" +
	"luaProgram\"<\n" +
	"\n" +
	"LuaProgram\x12\x16\n" +
	"\x06source\x18\x01 \x01(\fR\x06source\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\"?\n" +
	"\rWriteResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.sink.v1.WriteResultR\aresults\"\xc4\x01\n" +
	"\vWriteResult\x12'\n" +
	"\x0foperation_index\x18\x01 \x01(\rR\x0eoperationIndex\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.sink.v1.WriteStatusR\x06status\x122\n" +
	"\brevision\x18\x03 \x01(\v2\x16.sink.v1.RevisionTokenR\brevision\x12*\n" +
	"\afailure\x18\x04 \x01(\v2\x10.sink.v1.FailureR\afailure\"\x8b\x01\n" +
	"\rDeleteRequest\x12@\n" +
	"\x0fcompletion_mode\x18\x01 \x01(\x0e2\x17.sink.v1.CompletionModeR\x0ecompletionMode\x128\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x18.sink.v1.DeleteOperationR\n" +
	"operations\"C\n" +
	"\x0fDeleteOperation\x120\n" +
	"\aaddress\x18\x01 \x01(\v2\x16.sink.v1.RecordAddressR\aaddress\"A\n" +
	"\x0eDeleteResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.sink.v1.DeleteResultR\aresults\"\x92\x01\n" +
	"\fDeleteResult\x12'\n" +
	"\x0foperation_index\x18\x01 \x01(\rR\x0eoperationIndex\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.sink.v1.DeleteStatusR\x06status\x12*\n" +
	"\afailure\x18\x03 \x01(\v2\x10.sink.v1.FailureR\afailure\"k\n" +
	"\aFailure\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.sink.v1.FailureCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable*\xac\x01\n" +
	"\x0eCompletionMode\x12\x1f\n" +
	"\x1bCOMPLETION_MODE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"COMPLETION_MODE_WAIT_UNTIL_APPLIED\x10\x01\x12)\n" +
	"%COMPLETION_MODE_RETURN_AFTER_ACCEPTED\x10\x02\x12&\n" +
	"\"COMPLETION_MODE_WAIT_UNTIL_VISIBLE\x10\x03*s\n" +
	"\n" +
	"ReadStatus\x12\x1b\n" +
	"\x17READ_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11READ_STATUS_FOUND\x10\x01\x12\x19\n" +
	"\x15READ_STATUS_NOT_FOUND\x10\x02\x12\x16\n" +
	"\x12READ_STATUS_FAILED\x10\x03*m\n" +
	"\tWriteMode\x12\x1a\n" +
	"\x16WRITE_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WRITE_MODE_CREATE\x10\x01\x12\x16\n" +
	"\x12WRITE_MODE_REPLACE\x10\x02\x12\x15\n" +
	"\x11WRITE_MODE_UPSERT\x10\x03*~\n" +
	"\x13MissingDocumentMode\x12%\n" +
	"!MISSING_DOCUMENT_MODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aMISSING_DOCUMENT_MODE_FAIL\x10\x01\x12 \n" +
	"\x1cMISSING_DOCUMENT_MODE_CREATE\x10\x02*\x9f\x01\n" +
	"\vWriteStatus\x12\x1c\n" +
	"\x18WRITE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WRITE_STATUS_ACCEPTED\x10\x01\x12\x18\n" +
	"\x14WRITE_STATUS_APPLIED\x10\x02\x12$\n" +
	" WRITE_STATUS_PRECONDITION_FAILED\x10\x03\x12\x17\n" +
	"\x13WRITE_STATUS_FAILED\x10\x04*~\n" +
	"\fDeleteStatus\x12\x1d\n" +
	"\x19DELETE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DELETE_STATUS_ACCEPTED\x10\x01\x12\x19\n" +
	"\x15DELETE_STATUS_APPLIED\x10\x02\x12\x18\n" +
	"\x14DELETE_STATUS_FAILED\x10\x03*\xad\x02\n" +
	"\vFailureCode\x12\x1c\n" +
	"\x18FAILURE_CODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dFAILURE_CODE_INVALID_ARGUMENT\x10\x01\x12$\n" +
	" FAILURE_CODE_PRECONDITION_FAILED\x10\x02\x12\x1a\n" +
	"\x16FAILURE_CODE_NOT_FOUND\x10\x03\x12\x19\n" +
	"\x15FAILURE_CODE_CONFLICT\x10\x04\x12#\n" +
	"\x1fFAILURE_CODE_RESOURCE_EXHAUSTED\x10\x05\x12\x1c\n" +
	"\x18FAILURE_CODE_UNAVAILABLE\x10\x06\x12\"\n" +
	"\x1eFAILURE_CODE_DEADLINE_EXCEEDED\x10\a\x12\x19\n" +
	"\x15FAILURE_CODE_INTERNAL\x10\b2\xae\x01\n" +
	"\x04Sink\x123\n" +
	"\x04Read\x12\x14.sink.v1.ReadRequest\x1a\x15.sink.v1.ReadResponse\x126\n" +
	"\x05Write\x12\x15.sink.v1.WriteRequest\x1a\x16.sink.v1.WriteResponse\x129\n" +
	"\x06Delete\x12\x16.sink.v1.DeleteRequest\x1a\x17.sink.v1.DeleteResponseB-Z+github.com/liran/sink-go/api/sink/v1;sinkv1b\x06proto3"

var (
	file_sink_sink_proto_rawDescOnce sync.Once
	file_sink_sink_proto_rawDescData []byte
)

func file_sink_sink_proto_rawDescGZIP() []byte {
	file_sink_sink_proto_rawDescOnce.Do(func() {
		file_sink_sink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sink_sink_proto_rawDesc), len(file_sink_sink_proto_rawDesc)))
	})
	return file_sink_sink_proto_rawDescData
}

var file_sink_sink_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_sink_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_sink_sink_proto_goTypes = []any{
	(CompletionMode)(0),      // 0: sink.v1.CompletionMode
	(ReadStatus)(0),          // 1: sink.v1.ReadStatus
	(WriteMode)(0),           // 2: sink.v1.WriteMode
	(MissingDocumentMode)(0), // 3: sink.v1.MissingDocumentMode
	(WriteStatus)(0),         // 4: sink.v1.WriteStatus
	(DeleteStatus)(0),        // 5: sink.v1.DeleteStatus
	(FailureCode)(0),         // 6: sink.v1.FailureCode
	(*RecordAddress)(nil),    // 7: sink.v1.RecordAddress
	(*RecordKey)(nil),        // 8: sink.v1.RecordKey
	(*OpaqueValue)(nil),      // 9: sink.v1.OpaqueValue
	(*Document)(nil),         // 10: sink.v1.Document
	(*RevisionToken)(nil),    // 11: sink.v1.RevisionToken
	(*ReadRequest)(nil),      // 12: sink.v1.ReadRequest
	(*ReadOperation)(nil),    // 13: sink.v1.ReadOperation
	(*ReadResponse)(nil),     // 14: sink.v1.ReadResponse
	(*ReadResult)(nil),       // 15: sink.v1.ReadResult
	(*WriteRequest)(nil),     // 16: sink.v1.WriteRequest
	(*WriteOperation)(nil),   // 17: sink.v1.WriteOperation
	(*PutOperation)(nil),     // 18: sink.v1.PutOperation
	(*MergeOperation)(nil),   // 19: sink.v1.MergeOperation
	(*LuaProgram)(nil),       // 20: sink.v1.LuaProgram
	(*WriteResponse)(nil),    // 21: sink.v1.WriteResponse
	(*WriteResult)(nil),      // 22: sink.v1.WriteResult
	(*DeleteRequest)(nil),    // 23: sink.v1.DeleteRequest
	(*DeleteOperation)(nil),  // 24: sink.v1.DeleteOperation
	(*DeleteResponse)(nil),   // 25: sink.v1.DeleteResponse
	(*DeleteResult)(nil),     // 26: sink.v1.DeleteResult
	(*Failure)(nil),          // 27: sink.v1.Failure
}
var file_sink_sink_proto_depIdxs = []int32{
	8,  // 0: sink.v1.RecordAddress.key:type_name -> sink.v1.RecordKey
	9,  // 1: sink.v1.RecordKey.opaque_value:type_name -> sink.v1.OpaqueValue
	13, // 2: sink.v1.ReadRequest.operations:type_name -> sink.v1.ReadOperation
	7,  // 3: sink.v1.ReadOperation.address:type_name -> sink.v1.RecordAddress
	15, // 4: sink.v1.ReadResponse.results:type_name -> sink.v1.ReadResult
	1,  // 5: sink.v1.ReadResult.status:type_name -> sink.v1.ReadStatus
	10, // 6: sink.v1.ReadResult.document:type_name -> sink.v1.Document
	11, // 7: sink.v1.ReadResult.revision:type_name -> sink.v1.RevisionToken
	27, // 8: sink.v1.ReadResult.failure:type_name -> sink.v1.Failure
	0,  // 9: sink.v1.WriteRequest.completion_mode:type_name -> sink.v1.CompletionMode
	17, // 10: sink.v1.WriteRequest.operations:type_name -> sink.v1.WriteOperation
	20, // 11: sink.v1.WriteRequest.lua_programs:type_name -> sink.v1.LuaProgram
	7,  // 12: sink.v1.WriteOperation.address:type_name -> sink.v1.RecordAddress
	18, // 13: sink.v1.WriteOperation.put:type_name -> sink.v1.PutOperation
	19, // 14: sink.v1.WriteOperation.merge:type_name -> sink.v1.MergeOperation
	10, // 15: sink.v1.PutOperation.document:type_name -> sink.v1.Document
	2,  // 16: sink.v1.PutOperation.mode:type_name -> sink.v1.WriteMode
	10, // 17: sink.v1.MergeOperation.incoming_document:type_name -> sink.v1.Document
	3,  // 18: sink.v1.MergeOperation.missing_document_mode:type_name -> sink.v1.MissingDocumentMode
	20, // 19: sink.v1.MergeOperation.lua_program:type_name -> sink.v1.LuaProgram
	22, // 20: sink.v1.WriteResponse.results:type_name -> sink.v1.WriteResult
	4,  // 21: sink.v1.WriteResult.status:type_name -> sink.v1.WriteStatus
	11, // 22: sink.v1.WriteResult.revision:type_name -> sink.v1.RevisionToken
	27, // 23: sink.v1.WriteResult.failure:type_name -> sink.v1.Failure
	0,  // 24: sink.v1.DeleteRequest.completion_mode:type_name -> sink.v1.CompletionMode
	24, // 25: sink.v1.DeleteRequest.operations:type_name -> sink.v1.DeleteOperation
	7,  // 26: sink.v1.DeleteOperation.address:type_name -> sink.v1.RecordAddress
	26, // 27: sink.v1.DeleteResponse.results:type_name -> sink.v1.DeleteResult
	5,  // 28: sink.v1.DeleteResult.status:type_name -> sink.v1.DeleteStatus
	27, // 29: sink.v1.DeleteResult.failure:type_name -> sink.v1.Failure
	6,  // 30: sink.v1.Failure.code:type_name -> sink.v1.FailureCode
	12, // 31: sink.v1.Sink.Read:input_type -> sink.v1.ReadRequest
	16, // 32: sink.v1.Sink.Write:input_type -> sink.v1.WriteRequest
	23, // 33: sink.v1.Sink.Delete:input_type -> sink.v1.DeleteRequest
	14, // 34: sink.v1.Sink.Read:output_type -> sink.v1.ReadResponse
	21, // 35: sink.v1.Sink.Write:output_type -> sink.v1.WriteResponse
	25, // 36: sink.v1.Sink.Delete:output_type -> sink.v1.DeleteResponse
	34, // [34:37] is the sub-list for method output_type
	31, // [31:34] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_sink_sink_proto_init() }
func file_sink_sink_proto_init() {
	if File_sink_sink_proto != nil {
		return
	}
	file_sink_sink_proto_msgTypes[1].OneofWrappers = []any{
		(*RecordKey_StringValue)(nil),
		(*RecordKey_Int64Value)(nil),
		(*RecordKey_BytesValue)(nil),
		(*RecordKey_OpaqueValue)(nil),
	}
	file_sink_sink_proto_msgTypes[10].OneofWrappers = []any{
		(*WriteOperation_Put)(nil),
		(*WriteOperation_Merge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sink_sink_proto_rawDesc), len(file_sink_sink_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sink_sink_proto_goTypes,
		DependencyIndexes: file_sink_sink_proto_depIdxs,
		EnumInfos:         file_sink_sink_proto_enumTypes,
		MessageInfos:      file_sink_sink_proto_msgTypes,
	}.Build()
	File_sink_sink_proto = out.File
	file_sink_sink_proto_goTypes = nil
	file_sink_sink_proto_depIdxs = nil
}
