// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: sink/sink.proto

package sinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentEncoding int32

const (
	DocumentEncoding_DOCUMENT_ENCODING_UNSPECIFIED DocumentEncoding = 0
	DocumentEncoding_DOCUMENT_ENCODING_JSON        DocumentEncoding = 1
	DocumentEncoding_DOCUMENT_ENCODING_BSON        DocumentEncoding = 2
)

// Enum value maps for DocumentEncoding.
var (
	DocumentEncoding_name = map[int32]string{
		0: "DOCUMENT_ENCODING_UNSPECIFIED",
		1: "DOCUMENT_ENCODING_JSON",
		2: "DOCUMENT_ENCODING_BSON",
	}
	DocumentEncoding_value = map[string]int32{
		"DOCUMENT_ENCODING_UNSPECIFIED": 0,
		"DOCUMENT_ENCODING_JSON":        1,
		"DOCUMENT_ENCODING_BSON":        2,
	}
)

func (x DocumentEncoding) Enum() *DocumentEncoding {
	p := new(DocumentEncoding)
	*p = x
	return p
}

func (x DocumentEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[0].Descriptor()
}

func (DocumentEncoding) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[0]
}

func (x DocumentEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentEncoding.Descriptor instead.
func (DocumentEncoding) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{0}
}

// CompletionMode defines the point at which a mutating RPC returns success.
type CompletionMode int32

const (
	CompletionMode_COMPLETION_MODE_UNSPECIFIED CompletionMode = 0
	// Wait until the storage adapter has applied each operation.
	CompletionMode_COMPLETION_MODE_WAIT_UNTIL_APPLIED CompletionMode = 1
	// Return after a durable asynchronous queue has accepted each operation.
	// Acceptance does not mean that the storage adapter has applied it.
	CompletionMode_COMPLETION_MODE_RETURN_AFTER_ACCEPTED CompletionMode = 2
	// Wait until the storage adapter has applied each operation and made the
	// result visible to subsequent reads. Search adapters use refresh=wait_for.
	CompletionMode_COMPLETION_MODE_WAIT_UNTIL_VISIBLE CompletionMode = 3
)

// Enum value maps for CompletionMode.
var (
	CompletionMode_name = map[int32]string{
		0: "COMPLETION_MODE_UNSPECIFIED",
		1: "COMPLETION_MODE_WAIT_UNTIL_APPLIED",
		2: "COMPLETION_MODE_RETURN_AFTER_ACCEPTED",
		3: "COMPLETION_MODE_WAIT_UNTIL_VISIBLE",
	}
	CompletionMode_value = map[string]int32{
		"COMPLETION_MODE_UNSPECIFIED":           0,
		"COMPLETION_MODE_WAIT_UNTIL_APPLIED":    1,
		"COMPLETION_MODE_RETURN_AFTER_ACCEPTED": 2,
		"COMPLETION_MODE_WAIT_UNTIL_VISIBLE":    3,
	}
)

func (x CompletionMode) Enum() *CompletionMode {
	p := new(CompletionMode)
	*p = x
	return p
}

func (x CompletionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompletionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[1].Descriptor()
}

func (CompletionMode) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[1]
}

func (x CompletionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompletionMode.Descriptor instead.
func (CompletionMode) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{1}
}

type ReadStatus int32

const (
	ReadStatus_READ_STATUS_UNSPECIFIED ReadStatus = 0
	ReadStatus_READ_STATUS_FOUND       ReadStatus = 1
	ReadStatus_READ_STATUS_NOT_FOUND   ReadStatus = 2
	ReadStatus_READ_STATUS_FAILED      ReadStatus = 3
)

// Enum value maps for ReadStatus.
var (
	ReadStatus_name = map[int32]string{
		0: "READ_STATUS_UNSPECIFIED",
		1: "READ_STATUS_FOUND",
		2: "READ_STATUS_NOT_FOUND",
		3: "READ_STATUS_FAILED",
	}
	ReadStatus_value = map[string]int32{
		"READ_STATUS_UNSPECIFIED": 0,
		"READ_STATUS_FOUND":       1,
		"READ_STATUS_NOT_FOUND":   2,
		"READ_STATUS_FAILED":      3,
	}
)

func (x ReadStatus) Enum() *ReadStatus {
	p := new(ReadStatus)
	*p = x
	return p
}

func (x ReadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[2].Descriptor()
}

func (ReadStatus) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[2]
}

func (x ReadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadStatus.Descriptor instead.
func (ReadStatus) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{2}
}

type WriteMode int32

const (
	WriteMode_WRITE_MODE_UNSPECIFIED WriteMode = 0
	WriteMode_WRITE_MODE_CREATE      WriteMode = 1
	WriteMode_WRITE_MODE_REPLACE     WriteMode = 2
	WriteMode_WRITE_MODE_UPSERT      WriteMode = 3
)

// Enum value maps for WriteMode.
var (
	WriteMode_name = map[int32]string{
		0: "WRITE_MODE_UNSPECIFIED",
		1: "WRITE_MODE_CREATE",
		2: "WRITE_MODE_REPLACE",
		3: "WRITE_MODE_UPSERT",
	}
	WriteMode_value = map[string]int32{
		"WRITE_MODE_UNSPECIFIED": 0,
		"WRITE_MODE_CREATE":      1,
		"WRITE_MODE_REPLACE":     2,
		"WRITE_MODE_UPSERT":      3,
	}
)

func (x WriteMode) Enum() *WriteMode {
	p := new(WriteMode)
	*p = x
	return p
}

func (x WriteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[3].Descriptor()
}

func (WriteMode) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[3]
}

func (x WriteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteMode.Descriptor instead.
func (WriteMode) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{3}
}

type WriteStatus int32

const (
	WriteStatus_WRITE_STATUS_UNSPECIFIED WriteStatus = 0
	// The asynchronous queue accepted the operation durably.
	WriteStatus_WRITE_STATUS_ACCEPTED WriteStatus = 1
	// The storage adapter applied the operation.
	WriteStatus_WRITE_STATUS_APPLIED WriteStatus = 2
	// A CREATE, REPLACE, or adapter-level revision condition did not match.
	WriteStatus_WRITE_STATUS_PRECONDITION_FAILED WriteStatus = 3
	WriteStatus_WRITE_STATUS_FAILED              WriteStatus = 4
)

// Enum value maps for WriteStatus.
var (
	WriteStatus_name = map[int32]string{
		0: "WRITE_STATUS_UNSPECIFIED",
		1: "WRITE_STATUS_ACCEPTED",
		2: "WRITE_STATUS_APPLIED",
		3: "WRITE_STATUS_PRECONDITION_FAILED",
		4: "WRITE_STATUS_FAILED",
	}
	WriteStatus_value = map[string]int32{
		"WRITE_STATUS_UNSPECIFIED":         0,
		"WRITE_STATUS_ACCEPTED":            1,
		"WRITE_STATUS_APPLIED":             2,
		"WRITE_STATUS_PRECONDITION_FAILED": 3,
		"WRITE_STATUS_FAILED":              4,
	}
)

func (x WriteStatus) Enum() *WriteStatus {
	p := new(WriteStatus)
	*p = x
	return p
}

func (x WriteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[4].Descriptor()
}

func (WriteStatus) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[4]
}

func (x WriteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteStatus.Descriptor instead.
func (WriteStatus) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{4}
}

type DeleteStatus int32

const (
	DeleteStatus_DELETE_STATUS_UNSPECIFIED DeleteStatus = 0
	DeleteStatus_DELETE_STATUS_ACCEPTED    DeleteStatus = 1
	DeleteStatus_DELETE_STATUS_APPLIED     DeleteStatus = 2
	DeleteStatus_DELETE_STATUS_FAILED      DeleteStatus = 3
)

// Enum value maps for DeleteStatus.
var (
	DeleteStatus_name = map[int32]string{
		0: "DELETE_STATUS_UNSPECIFIED",
		1: "DELETE_STATUS_ACCEPTED",
		2: "DELETE_STATUS_APPLIED",
		3: "DELETE_STATUS_FAILED",
	}
	DeleteStatus_value = map[string]int32{
		"DELETE_STATUS_UNSPECIFIED": 0,
		"DELETE_STATUS_ACCEPTED":    1,
		"DELETE_STATUS_APPLIED":     2,
		"DELETE_STATUS_FAILED":      3,
	}
)

func (x DeleteStatus) Enum() *DeleteStatus {
	p := new(DeleteStatus)
	*p = x
	return p
}

func (x DeleteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[5].Descriptor()
}

func (DeleteStatus) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[5]
}

func (x DeleteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteStatus.Descriptor instead.
func (DeleteStatus) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{5}
}

type FailureCode int32

const (
	FailureCode_FAILURE_CODE_UNSPECIFIED         FailureCode = 0
	FailureCode_FAILURE_CODE_INVALID_ARGUMENT    FailureCode = 1
	FailureCode_FAILURE_CODE_PRECONDITION_FAILED FailureCode = 2
	FailureCode_FAILURE_CODE_NOT_FOUND           FailureCode = 3
	FailureCode_FAILURE_CODE_CONFLICT            FailureCode = 4
	FailureCode_FAILURE_CODE_RESOURCE_EXHAUSTED  FailureCode = 5
	FailureCode_FAILURE_CODE_UNAVAILABLE         FailureCode = 6
	FailureCode_FAILURE_CODE_DEADLINE_EXCEEDED   FailureCode = 7
	FailureCode_FAILURE_CODE_INTERNAL            FailureCode = 8
)

// Enum value maps for FailureCode.
var (
	FailureCode_name = map[int32]string{
		0: "FAILURE_CODE_UNSPECIFIED",
		1: "FAILURE_CODE_INVALID_ARGUMENT",
		2: "FAILURE_CODE_PRECONDITION_FAILED",
		3: "FAILURE_CODE_NOT_FOUND",
		4: "FAILURE_CODE_CONFLICT",
		5: "FAILURE_CODE_RESOURCE_EXHAUSTED",
		6: "FAILURE_CODE_UNAVAILABLE",
		7: "FAILURE_CODE_DEADLINE_EXCEEDED",
		8: "FAILURE_CODE_INTERNAL",
	}
	FailureCode_value = map[string]int32{
		"FAILURE_CODE_UNSPECIFIED":         0,
		"FAILURE_CODE_INVALID_ARGUMENT":    1,
		"FAILURE_CODE_PRECONDITION_FAILED": 2,
		"FAILURE_CODE_NOT_FOUND":           3,
		"FAILURE_CODE_CONFLICT":            4,
		"FAILURE_CODE_RESOURCE_EXHAUSTED":  5,
		"FAILURE_CODE_UNAVAILABLE":         6,
		"FAILURE_CODE_DEADLINE_EXCEEDED":   7,
		"FAILURE_CODE_INTERNAL":            8,
	}
)

func (x FailureCode) Enum() *FailureCode {
	p := new(FailureCode)
	*p = x
	return p
}

func (x FailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_sink_sink_proto_enumTypes[6].Descriptor()
}

func (FailureCode) Type() protoreflect.EnumType {
	return &file_sink_sink_proto_enumTypes[6]
}

func (x FailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureCode.Descriptor instead.
func (FailureCode) EnumDescriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{6}
}

// RecordAddress identifies a record without exposing a physical database,
// collection, table, or primary-key field name.
type RecordAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Dataset       string                 `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Key           *RecordKey             `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAddress) Reset() {
	*x = RecordAddress{}
	mi := &file_sink_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAddress) ProtoMessage() {}

func (x *RecordAddress) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAddress.ProtoReflect.Descriptor instead.
func (*RecordAddress) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{0}
}

func (x *RecordAddress) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *RecordAddress) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RecordAddress) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *RecordAddress) GetKey() *RecordKey {
	if x != nil {
		return x.Key
	}
	return nil
}

// RecordKey is encoded deterministically so it can also be used for routing.
// Opaque keys preserve storage-specific legacy key types without teaching the
// Sink core how to interpret them.
type RecordKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RecordKey_StringValue
	//	*RecordKey_Int64Value
	//	*RecordKey_BytesValue
	//	*RecordKey_OpaqueValue
	Kind          isRecordKey_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordKey) Reset() {
	*x = RecordKey{}
	mi := &file_sink_sink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordKey) ProtoMessage() {}

func (x *RecordKey) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordKey.ProtoReflect.Descriptor instead.
func (*RecordKey) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{1}
}

func (x *RecordKey) GetKind() isRecordKey_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RecordKey) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*RecordKey_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *RecordKey) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*RecordKey_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *RecordKey) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*RecordKey_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *RecordKey) GetOpaqueValue() *OpaqueValue {
	if x != nil {
		if x, ok := x.Kind.(*RecordKey_OpaqueValue); ok {
			return x.OpaqueValue
		}
	}
	return nil
}

type isRecordKey_Kind interface {
	isRecordKey_Kind()
}

type RecordKey_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type RecordKey_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type RecordKey_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,3,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type RecordKey_OpaqueValue struct {
	OpaqueValue *OpaqueValue `protobuf:"bytes,4,opt,name=opaque_value,json=opaqueValue,proto3,oneof"`
}

func (*RecordKey_StringValue) isRecordKey_Kind() {}

func (*RecordKey_Int64Value) isRecordKey_Kind() {}

func (*RecordKey_BytesValue) isRecordKey_Kind() {}

func (*RecordKey_OpaqueValue) isRecordKey_Kind() {}

type OpaqueValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpaqueValue) Reset() {
	*x = OpaqueValue{}
	mi := &file_sink_sink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueValue) ProtoMessage() {}

func (x *OpaqueValue) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpaqueValue.ProtoReflect.Descriptor instead.
func (*OpaqueValue) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{2}
}

func (x *OpaqueValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OpaqueValue) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Document contains one explicitly encoded user object. Callers select JSON
// for search storage and BSON for MongoDB storage.
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoding      DocumentEncoding       `protobuf:"varint,1,opt,name=encoding,proto3,enum=sink.v1.DocumentEncoding" json:"encoding,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_sink_sink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{3}
}

func (x *Document) GetEncoding() DocumentEncoding {
	if x != nil {
		return x.Encoding
	}
	return DocumentEncoding_DOCUMENT_ENCODING_UNSPECIFIED
}

func (x *Document) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RevisionToken is interpreted only by the selected storage adapter.
type RevisionToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionToken) Reset() {
	*x = RevisionToken{}
	mi := &file_sink_sink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionToken) ProtoMessage() {}

func (x *RevisionToken) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionToken.ProtoReflect.Descriptor instead.
func (*RevisionToken) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{4}
}

func (x *RevisionToken) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*ReadOperation       `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_sink_sink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRequest) GetOperations() []*ReadOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ReadOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *RecordAddress         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOperation) Reset() {
	*x = ReadOperation{}
	mi := &file_sink_sink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOperation) ProtoMessage() {}

func (x *ReadOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOperation.ProtoReflect.Descriptor instead.
func (*ReadOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{6}
}

func (x *ReadOperation) GetAddress() *RecordAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results are returned in request order. operation_index is included to make
	// correlation explicit when an implementation executes records in parallel.
	Results       []*ReadResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_sink_sink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{7}
}

func (x *ReadResponse) GetResults() []*ReadResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReadResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationIndex uint32                 `protobuf:"varint,1,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	Status         ReadStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=sink.v1.ReadStatus" json:"status,omitempty"`
	Document       *Document              `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	Revision       *RevisionToken         `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Failure        *Failure               `protobuf:"bytes,5,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadResult) Reset() {
	*x = ReadResult{}
	mi := &file_sink_sink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResult) ProtoMessage() {}

func (x *ReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResult.ProtoReflect.Descriptor instead.
func (*ReadResult) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{8}
}

func (x *ReadResult) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *ReadResult) GetStatus() ReadStatus {
	if x != nil {
		return x.Status
	}
	return ReadStatus_READ_STATUS_UNSPECIFIED
}

func (x *ReadResult) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ReadResult) GetRevision() *RevisionToken {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *ReadResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type WriteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompletionMode CompletionMode         `protobuf:"varint,1,opt,name=completion_mode,json=completionMode,proto3,enum=sink.v1.CompletionMode" json:"completion_mode,omitempty"`
	// Operations for the same address are executed in request order. Operations
	// for different addresses may execute concurrently.
	Operations []*WriteOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// Programs can be declared once and referenced by digest from multiple merge
	// operations, avoiding repeated Lua source bytes in a synchronous batch.
	LuaPrograms   []*LuaProgram `protobuf:"bytes,3,rep,name=lua_programs,json=luaPrograms,proto3" json:"lua_programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_sink_sink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{9}
}

func (x *WriteRequest) GetCompletionMode() CompletionMode {
	if x != nil {
		return x.CompletionMode
	}
	return CompletionMode_COMPLETION_MODE_UNSPECIFIED
}

func (x *WriteRequest) GetOperations() []*WriteOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *WriteRequest) GetLuaPrograms() []*LuaProgram {
	if x != nil {
		return x.LuaPrograms
	}
	return nil
}

type WriteOperation struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address *RecordAddress         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Return the logical document submitted by this operation after its commit.
	// Only synchronous completion modes support this. These operations do not
	// share a folded commit with preceding or following operations.
	ReturnDocument bool `protobuf:"varint,4,opt,name=return_document,json=returnDocument,proto3" json:"return_document,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*WriteOperation_Put
	//	*WriteOperation_Merge
	Action        isWriteOperation_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOperation) Reset() {
	*x = WriteOperation{}
	mi := &file_sink_sink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOperation) ProtoMessage() {}

func (x *WriteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOperation.ProtoReflect.Descriptor instead.
func (*WriteOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{10}
}

func (x *WriteOperation) GetAddress() *RecordAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *WriteOperation) GetReturnDocument() bool {
	if x != nil {
		return x.ReturnDocument
	}
	return false
}

func (x *WriteOperation) GetAction() isWriteOperation_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *WriteOperation) GetPut() *PutOperation {
	if x != nil {
		if x, ok := x.Action.(*WriteOperation_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *WriteOperation) GetMerge() *MergeOperation {
	if x != nil {
		if x, ok := x.Action.(*WriteOperation_Merge); ok {
			return x.Merge
		}
	}
	return nil
}

type isWriteOperation_Action interface {
	isWriteOperation_Action()
}

type WriteOperation_Put struct {
	Put *PutOperation `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type WriteOperation_Merge struct {
	Merge *MergeOperation `protobuf:"bytes,3,opt,name=merge,proto3,oneof"`
}

func (*WriteOperation_Put) isWriteOperation_Action() {}

func (*WriteOperation_Merge) isWriteOperation_Action() {}

// PutOperation writes a complete user document without interpreting its fields.
type PutOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Mode          WriteMode              `protobuf:"varint,2,opt,name=mode,proto3,enum=sink.v1.WriteMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutOperation) Reset() {
	*x = PutOperation{}
	mi := &file_sink_sink_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOperation) ProtoMessage() {}

func (x *PutOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOperation.ProtoReflect.Descriptor instead.
func (*PutOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{11}
}

func (x *PutOperation) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *PutOperation) GetMode() WriteMode {
	if x != nil {
		return x.Mode
	}
	return WriteMode_WRITE_MODE_UNSPECIFIED
}

// MergeOperation carries the original merge intent. In asynchronous mode Sink
// expands any program reference before queueing the operation so the worker can
// merge against the document version it reads at execution time.
type MergeOperation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncomingDocument *Document              `protobuf:"bytes,1,opt,name=incoming_document,json=incomingDocument,proto3" json:"incoming_document,omitempty"`
	LuaProgram       *LuaProgram            `protobuf:"bytes,3,opt,name=lua_program,json=luaProgram,proto3" json:"lua_program,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MergeOperation) Reset() {
	*x = MergeOperation{}
	mi := &file_sink_sink_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeOperation) ProtoMessage() {}

func (x *MergeOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeOperation.ProtoReflect.Descriptor instead.
func (*MergeOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{12}
}

func (x *MergeOperation) GetIncomingDocument() *Document {
	if x != nil {
		return x.IncomingDocument
	}
	return nil
}

func (x *MergeOperation) GetLuaProgram() *LuaProgram {
	if x != nil {
		return x.LuaProgram
	}
	return nil
}

// LuaProgram is self-contained so merge rules can be versioned and deployed
// with the calling application instead of being registered in Sink.
type LuaProgram struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source may be omitted from a merge operation when the matching full program
	// is present in WriteRequest.lua_programs. Workers always receive full source.
	Source []byte `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Optional SHA-256 digest. Sink verifies it when present and always uses the
	// computed digest as the compiled-program cache key.
	Sha256        []byte `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuaProgram) Reset() {
	*x = LuaProgram{}
	mi := &file_sink_sink_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuaProgram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuaProgram) ProtoMessage() {}

func (x *LuaProgram) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuaProgram.ProtoReflect.Descriptor instead.
func (*LuaProgram) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{13}
}

func (x *LuaProgram) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LuaProgram) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*WriteResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_sink_sink_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{14}
}

func (x *WriteResponse) GetResults() []*WriteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type WriteResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationIndex uint32                 `protobuf:"varint,1,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	Status         WriteStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=sink.v1.WriteStatus" json:"status,omitempty"`
	Revision       *RevisionToken         `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Failure        *Failure               `protobuf:"bytes,4,opt,name=failure,proto3" json:"failure,omitempty"`
	Document       *Document              `protobuf:"bytes,5,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteResult) Reset() {
	*x = WriteResult{}
	mi := &file_sink_sink_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResult) ProtoMessage() {}

func (x *WriteResult) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResult.ProtoReflect.Descriptor instead.
func (*WriteResult) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{15}
}

func (x *WriteResult) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *WriteResult) GetStatus() WriteStatus {
	if x != nil {
		return x.Status
	}
	return WriteStatus_WRITE_STATUS_UNSPECIFIED
}

func (x *WriteResult) GetRevision() *RevisionToken {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *WriteResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *WriteResult) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompletionMode CompletionMode         `protobuf:"varint,1,opt,name=completion_mode,json=completionMode,proto3,enum=sink.v1.CompletionMode" json:"completion_mode,omitempty"`
	// Deletes are hard deletes. Deleting an absent record is successful.
	Operations    []*DeleteOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_sink_sink_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteRequest) GetCompletionMode() CompletionMode {
	if x != nil {
		return x.CompletionMode
	}
	return CompletionMode_COMPLETION_MODE_UNSPECIFIED
}

func (x *DeleteRequest) GetOperations() []*DeleteOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type DeleteOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *RecordAddress         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOperation) Reset() {
	*x = DeleteOperation{}
	mi := &file_sink_sink_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOperation) ProtoMessage() {}

func (x *DeleteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOperation.ProtoReflect.Descriptor instead.
func (*DeleteOperation) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteOperation) GetAddress() *RecordAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DeleteResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_sink_sink_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResponse) GetResults() []*DeleteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationIndex uint32                 `protobuf:"varint,1,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	Status         DeleteStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=sink.v1.DeleteStatus" json:"status,omitempty"`
	Failure        *Failure               `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	mi := &file_sink_sink_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteResult) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *DeleteResult) GetStatus() DeleteStatus {
	if x != nil {
		return x.Status
	}
	return DeleteStatus_DELETE_STATUS_UNSPECIFIED
}

func (x *DeleteResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          FailureCode            `protobuf:"varint,1,opt,name=code,proto3,enum=sink.v1.FailureCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_sink_sink_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{20}
}

func (x *Failure) GetCode() FailureCode {
	if x != nil {
		return x.Code
	}
	return FailureCode_FAILURE_CODE_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Failure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// Command is the common input for Execute, Query, Count and Scan. Store configuration selects
// the adapter, which reads and validates the fields it needs. There is no
// backend-specific message branch or additional Sink envelope inside payload.
// Fields not used by an adapter must be empty.
//
// Current adapter mappings:
//   - MongoDB: store, namespace, content_type and payload. Namespace is the
//     database; payload is the complete ordered BSON command document, including
//     the command name and collection when applicable. Use application/bson.
//   - HTTP search: store, method, path, query, headers, content_type and payload.
//     Payload is the original request body, such as JSON or NDJSON. Namespace is
//     unused; resource selection is already expressed by path and the native body.
//
// These are native operations: payload retains the selected backend's syntax.
// SDK helpers can serialize native values directly into payload without callers
// constructing a separate Sink-specific command envelope.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required logical store. Endpoints and credentials come from server config.
	Store string `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	// Execution scope, such as a database name, when the adapter requires one.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Request method, such as GET or POST, when the adapter uses request methods.
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// Absolute path within the configured endpoint, never a URL. No host, query,
	// fragment or traversal segments; escaped resource IDs are supported.
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// URL-encoded query parameters without a leading '?'; repeated keys are valid.
	Query string `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	// Repeated values are preserved. Authentication and transport-owned headers
	// remain server-controlled. Set Content-Type using content_type, not headers.
	Headers []*Header `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`
	// Payload media type, e.g. application/bson, application/json or
	// application/x-ndjson. Required when payload is nonempty. This describes the
	// native encoding, not a separately versioned Sink payload schema.
	ContentType string `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Original command document or request body bytes. Keep native scalar types,
	// field order and bulk framing intact; no custom protobuf value wrappers.
	Payload       []byte `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_sink_sink_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{21}
}

func (x *Command) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *Command) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Command) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Command) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Command) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Command) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Command) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_sink_sink_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{22}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Execute performs one native interaction. It does not provide cross-RPC
// session affinity. Adapters reject commands requiring session affinity or a
// client-managed session; supported cursor queries use Scan instead.
// Each adapter validates its supported operations before forwarding. MongoDB
// protects revisions on supported writes; HTTP search rejects index lifecycle
// and alias management, including unknown administrative write endpoints.
//
// Permitted writes retain backend semantics subject to adapter safeguards. They
// do not run Lua merges, record batching or asynchronous completion. Neither
// Sink nor its SDK should automatically replay Execute after an unknown outcome.
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_sink_sink_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{23}
}

func (x *ExecuteRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// A complete native reply retains its original payload, including backend error
// replies. Such replies use gRPC OK with success=false; validation, transport
// and capacity failures use gRPC errors. HTTP replies preserve the status,
// repeated headers and entity bytes; redirects are returned without following.
type ExecuteResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContentType string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload     []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Native command success, or HTTP 2xx. Callers must still inspect item-level
	// failures in batch responses. Document commands also check native write and
	// write-concern errors.
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// Native transport status when available; zero means no such status exists.
	StatusCode    uint32    `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       []*Header `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_sink_sink_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{24}
}

func (x *ExecuteResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecuteResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ExecuteResponse) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Query returns an independent page without retaining a cursor between RPCs.
// Supported sources are find/read-only aggregate command documents and HTTP
// _search requests. Documents have the same native result shape as Scan.
// Use a stable native sort with a unique tie-breaker for predictable pages.
// Concurrent changes may shift results; pagination does not provide a snapshot.
type QueryRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// One-based page number; zero selects page 1. Deep pages still incur backend
	// offset costs and are subject to the backend's result-window limits.
	Page uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Zero selects 100; maximum 1000. Query replaces native find skip/limit and
	// HTTP from/size. For aggregate, pagination follows the supplied pipeline.
	PageSize uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Ordered sort keys. Empty preserves the native sort; nonempty replaces find
	// or HTTP sorting. For aggregate, sort follows the supplied pipeline.
	Sort []*SortField `protobuf:"bytes,4,rep,name=sort,proto3" json:"sort,omitempty"`
	// Absent preserves native projection. Present replaces find projection or
	// HTTP _source selection; aggregate applies it after the pipeline and sort,
	// before pagination. An empty fields list selects all document fields.
	Projection    *Projection `protobuf:"bytes,5,opt,name=projection,proto3" json:"projection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_sink_sink_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{25}
}

func (x *QueryRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *QueryRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryRequest) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *QueryRequest) GetProjection() *Projection {
	if x != nil {
		return x.Projection
	}
	return nil
}

type SortField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Descending    bool                   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortField) Reset() {
	*x = SortField{}
	mi := &file_sink_sink_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{26}
}

func (x *SortField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortField) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

// Field names are native document paths (relative to _source for HTTP search).
// HTTP hit metadata is unchanged. Document stores retain their native rules for
// identity-field projection.
// Database-specific computed projections can remain in Command.payload.
type Projection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Exclude       bool                   `protobuf:"varint,2,opt,name=exclude,proto3" json:"exclude,omitempty"` // False includes listed fields; true excludes them.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Projection) Reset() {
	*x = Projection{}
	mi := &file_sink_sink_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Projection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Projection) ProtoMessage() {}

func (x *Projection) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Projection.ProtoReflect.Descriptor instead.
func (*Projection) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{27}
}

func (x *Projection) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Projection) GetExclude() bool {
	if x != nil {
		return x.Exclude
	}
	return false
}

type QueryResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Documents []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	// Determined by fetching one extra result, not by running Count. Result-window
	// limits apply to this extra result too. A byte limit fails the whole request;
	// it never produces a silently shortened page.
	HasMore       bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_sink_sink_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{28}
}

func (x *QueryResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *QueryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Count is an independent query, not an implicit part of Query. It accepts the
// same sources and counts matches before find/HTTP pagination; for aggregate it
// counts the output of the supplied pipeline. HTTP counts matching documents
// before collapse. Partial or timed-out counts fail the request.
// Count and Query are separate observations and may differ under concurrent writes.
type CountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MongoDB find with an absent or empty filter automatically uses collection
	// metadata when no options require exact execution. Filtered queries,
	// aggregate pipelines and HTTP search counts remain exact.
	Command       *Command `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_sink_sink_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{29}
}

func (x *CountRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type CountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Count uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// True when the backend used an estimate instead of counting matching rows.
	Estimated     bool `protobuf:"varint,2,opt,name=estimated,proto3" json:"estimated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_sink_sink_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{30}
}

func (x *CountResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CountResponse) GetEstimated() bool {
	if x != nil {
		return x.Estimated
	}
	return false
}

// Scan returns one live page. Supply the same Command on every call and pass
// next_cursor back as cursor after processing a page. Cursors carry the seek
// position across server restarts and do not expire; no database session
// survives a request. Task deadlines and checkpoint retention belong to callers.
// Concurrent changes can affect later pages and retries. Scan is not a snapshot.
type ScanRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Zero selects 100; maximum 1000. The byte limit may produce a smaller page.
	BatchSize uint32 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// Empty starts a new scan. Treat this continuation marker as opaque; it is
	// bound to Command and is not an authorization credential.
	Cursor        []byte `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_sink_sink_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{31}
}

func (x *ScanRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ScanRequest) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ScanRequest) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

// Documents retain native encodings: BSON documents or complete JSON hits.
// Failed requests return no page; callers may retry from their last saved
// cursor, with live-query semantics and idempotent business processing.
type ScanResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Documents []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	// Empty means the scan reached the end observed by this request. Commit a
	// checkpoint only after processing documents. No explicit close is needed.
	NextCursor    []byte `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_sink_sink_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_sink_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_sink_sink_proto_rawDescGZIP(), []int{32}
}

func (x *ScanResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ScanResponse) GetNextCursor() []byte {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

var File_sink_sink_proto protoreflect.FileDescriptor

const file_sink_sink_proto_rawDesc = "" +
	"\n" +
	"\x0fsink/sink.proto\x12\asink.v1\"\x83\x01\n" +
	"\rRecordAddress\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\adataset\x18\x03 \x01(\tR\adataset\x12$\n" +
	"\x03key\x18\x04 \x01(\v2\x12.sink.v1.RecordKeyR\x03key\"\xb9\x01\n" +
	"\tRecordKey\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12!\n" +
	"\vbytes_value\x18\x03 \x01(\fH\x00R\n" +
	"bytesValue\x129\n" +
	"\fopaque_value\x18\x04 \x01(\v2\x14.sink.v1.OpaqueValueH\x00R\vopaqueValueB\x06\n" +
	"\x04kind\"5\n" +
	"\vOpaqueValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"[\n" +
	"\bDocument\x125\n" +
	"\bencoding\x18\x01 \x01(\x0e2\x19.sink.v1.DocumentEncodingR\bencoding\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"#\n" +
	"\rRevisionToken\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"E\n" +
	"\vReadRequest\x126\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x16.sink.v1.ReadOperationR\n" +
	"operations\"A\n" +
	"\rReadOperation\x120\n" +
	"\aaddress\x18\x01 \x01(\v2\x16.sink.v1.RecordAddressR\aaddress\"=\n" +
	"\fReadResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.sink.v1.ReadResultR\aresults\"\xf1\x01\n" +
	"\n" +
	"ReadResult\x12'\n" +
	"\x0foperation_index\x18\x01 \x01(\rR\x0eoperationIndex\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.sink.v1.ReadStatusR\x06status\x12-\n" +
	"\bdocument\x18\x03 \x01(\v2\x11.sink.v1.DocumentR\bdocument\x122\n" +
	"\brevision\x18\x04 \x01(\v2\x16.sink.v1.RevisionTokenR\brevision\x12*\n" +
	"\afailure\x18\x05 \x01(\v2\x10.sink.v1.FailureR\afailure\"\xc1\x01\n" +
	"\fWriteRequest\x12@\n" +
	"\x0fcompletion_mode\x18\x01 \x01(\x0e2\x17.sink.v1.CompletionModeR\x0ecompletionMode\x127\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x17.sink.v1.WriteOperationR\n" +
	"operations\x126\n" +
	"\flua_programs\x18\x03 \x03(\v2\x13.sink.v1.LuaProgramR\vluaPrograms\"\xd1\x01\n" +
	"\x0eWriteOperation\x120\n" +
	"\aaddress\x18\x01 \x01(\v2\x16.sink.v1.RecordAddressR\aaddress\x12'\n" +
	"\x0freturn_document\x18\x04 \x01(\bR\x0ereturnDocument\x12)\n" +
	"\x03put\x18\x02 \x01(\v2\x15.sink.v1.PutOperationH\x00R\x03put\x12/\n" +
	"\x05merge\x18\x03 \x01(\v2\x17.sink.v1.MergeOperationH\x00R\x05mergeB\b\n" +
	"\x06action\"e\n" +
	"\fPutOperation\x12-\n" +
	"\bdocument\x18\x01 \x01(\v2\x11.sink.v1.DocumentR\bdocument\x12&\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x12.sink.v1.WriteModeR\x04mode\"\xa3\x01\n" +
	"\x0eMergeOperation\x12>\n" +
	"\x11incoming_document\x18\x01 \x01(\v2\x11.sink.v1.DocumentR\x10incomingDocument\x124\n" +
	"\vlua_program\x18\x03 \x01(\v2\x13.sink.v1.LuaProgramR\n" +
	"luaProgramJ\x04\b\x02\x10\x03R\x15missing_document_mode\"<\n" +
	"\n" +
	"LuaProgram\x12\x16\n" +
	"\x06source\x18\x01 \x01(\fR\x06source\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\"?\n" +
	"\rWriteResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.sink.v1.WriteResultR\aresults\"\xf3\x01\n" +
	"\vWriteResult\x12'\n" +
	"\x0foperation_index\x18\x01 \x01(\rR\x0eoperationIndex\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.sink.v1.WriteStatusR\x06status\x122\n" +
	"\brevision\x18\x03 \x01(\v2\x16.sink.v1.RevisionTokenR\brevision\x12*\n" +
	"\afailure\x18\x04 \x01(\v2\x10.sink.v1.FailureR\afailure\x12-\n" +
	"\bdocument\x18\x05 \x01(\v2\x11.sink.v1.DocumentR\bdocument\"\x8b\x01\n" +
	"\rDeleteRequest\x12@\n" +
	"\x0fcompletion_mode\x18\x01 \x01(\x0e2\x17.sink.v1.CompletionModeR\x0ecompletionMode\x128\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x18.sink.v1.DeleteOperationR\n" +
	"operations\"C\n" +
	"\x0fDeleteOperation\x120\n" +
	"\aaddress\x18\x01 \x01(\v2\x16.sink.v1.RecordAddressR\aaddress\"A\n" +
	"\x0eDeleteResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.sink.v1.DeleteResultR\aresults\"\x92\x01\n" +
	"\fDeleteResult\x12'\n" +
	"\x0foperation_index\x18\x01 \x01(\rR\x0eoperationIndex\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.sink.v1.DeleteStatusR\x06status\x12*\n" +
	"\afailure\x18\x03 \x01(\v2\x10.sink.v1.FailureR\afailure\"k\n" +
	"\aFailure\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.sink.v1.FailureCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\xe7\x01\n" +
	"\aCommand\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x12)\n" +
	"\aheaders\x18\x06 \x03(\v2\x0f.sink.v1.HeaderR\aheaders\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\"4\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"<\n" +
	"\x0eExecuteRequest\x12*\n" +
	"\acommand\x18\x01 \x01(\v2\x10.sink.v1.CommandR\acommand\"\xb4\x01\n" +
	"\x0fExecuteResponse\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\rR\n" +
	"statusCode\x12)\n" +
	"\aheaders\x18\x05 \x03(\v2\x0f.sink.v1.HeaderR\aheaders\"\xc8\x01\n" +
	"\fQueryRequest\x12*\n" +
	"\acommand\x18\x01 \x01(\v2\x10.sink.v1.CommandR\acommand\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12&\n" +
	"\x04sort\x18\x04 \x03(\v2\x12.sink.v1.SortFieldR\x04sort\x123\n" +
	"\n" +
	"projection\x18\x05 \x01(\v2\x13.sink.v1.ProjectionR\n" +
	"projection\"A\n" +
	"\tSortField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1e\n" +
	"\n" +
	"descending\x18\x02 \x01(\bR\n" +
	"descending\">\n" +
	"\n" +
	"Projection\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12\x18\n" +
	"\aexclude\x18\x02 \x01(\bR\aexclude\"[\n" +
	"\rQueryResponse\x12/\n" +
	"\tdocuments\x18\x01 \x03(\v2\x11.sink.v1.DocumentR\tdocuments\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\":\n" +
	"\fCountRequest\x12*\n" +
	"\acommand\x18\x01 \x01(\v2\x10.sink.v1.CommandR\acommand\"C\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\x12\x1c\n" +
	"\testimated\x18\x02 \x01(\bR\testimated\"p\n" +
	"\vScanRequest\x12*\n" +
	"\acommand\x18\x01 \x01(\v2\x10.sink.v1.CommandR\acommand\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\rR\tbatchSize\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\fR\x06cursor\"`\n" +
	"\fScanResponse\x12/\n" +
	"\tdocuments\x18\x01 \x03(\v2\x11.sink.v1.DocumentR\tdocuments\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\fR\n" +
	"nextCursor*m\n" +
	"\x10DocumentEncoding\x12!\n" +
	"\x1dDOCUMENT_ENCODING_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DOCUMENT_ENCODING_JSON\x10\x01\x12\x1a\n" +
	"\x16DOCUMENT_ENCODING_BSON\x10\x02*\xac\x01\n" +
	"\x0eCompletionMode\x12\x1f\n" +
	"\x1bCOMPLETION_MODE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"COMPLETION_MODE_WAIT_UNTIL_APPLIED\x10\x01\x12)\n" +
	"%COMPLETION_MODE_RETURN_AFTER_ACCEPTED\x10\x02\x12&\n" +
	"\"COMPLETION_MODE_WAIT_UNTIL_VISIBLE\x10\x03*s\n" +
	"\n" +
	"ReadStatus\x12\x1b\n" +
	"\x17READ_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11READ_STATUS_FOUND\x10\x01\x12\x19\n" +
	"\x15READ_STATUS_NOT_FOUND\x10\x02\x12\x16\n" +
	"\x12READ_STATUS_FAILED\x10\x03*m\n" +
	"\tWriteMode\x12\x1a\n" +
	"\x16WRITE_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WRITE_MODE_CREATE\x10\x01\x12\x16\n" +
	"\x12WRITE_MODE_REPLACE\x10\x02\x12\x15\n" +
	"\x11WRITE_MODE_UPSERT\x10\x03*\x9f\x01\n" +
	"\vWriteStatus\x12\x1c\n" +
	"\x18WRITE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WRITE_STATUS_ACCEPTED\x10\x01\x12\x18\n" +
	"\x14WRITE_STATUS_APPLIED\x10\x02\x12$\n" +
	" WRITE_STATUS_PRECONDITION_FAILED\x10\x03\x12\x17\n" +
	"\x13WRITE_STATUS_FAILED\x10\x04*~\n" +
	"\fDeleteStatus\x12\x1d\n" +
	"\x19DELETE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DELETE_STATUS_ACCEPTED\x10\x01\x12\x19\n" +
	"\x15DELETE_STATUS_APPLIED\x10\x02\x12\x18\n" +
	"\x14DELETE_STATUS_FAILED\x10\x03*\xad\x02\n" +
	"\vFailureCode\x12\x1c\n" +
	"\x18FAILURE_CODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dFAILURE_CODE_INVALID_ARGUMENT\x10\x01\x12$\n" +
	" FAILURE_CODE_PRECONDITION_FAILED\x10\x02\x12\x1a\n" +
	"\x16FAILURE_CODE_NOT_FOUND\x10\x03\x12\x19\n" +
	"\x15FAILURE_CODE_CONFLICT\x10\x04\x12#\n" +
	"\x1fFAILURE_CODE_RESOURCE_EXHAUSTED\x10\x05\x12\x1c\n" +
	"\x18FAILURE_CODE_UNAVAILABLE\x10\x06\x12\"\n" +
	"\x1eFAILURE_CODE_DEADLINE_EXCEEDED\x10\a\x12\x19\n" +
	"\x15FAILURE_CODE_INTERNAL\x10\b2\x91\x03\n" +
	"\x04Sink\x123\n" +
	"\x04Read\x12\x14.sink.v1.ReadRequest\x1a\x15.sink.v1.ReadResponse\x126\n" +
	"\x05Write\x12\x15.sink.v1.WriteRequest\x1a\x16.sink.v1.WriteResponse\x129\n" +
	"\x06Delete\x12\x16.sink.v1.DeleteRequest\x1a\x17.sink.v1.DeleteResponse\x12<\n" +
	"\aExecute\x12\x17.sink.v1.ExecuteRequest\x1a\x18.sink.v1.ExecuteResponse\x126\n" +
	"\x05Query\x12\x15.sink.v1.QueryRequest\x1a\x16.sink.v1.QueryResponse\x126\n" +
	"\x05Count\x12\x15.sink.v1.CountRequest\x1a\x16.sink.v1.CountResponse\x123\n" +
	"\x04Scan\x12\x14.sink.v1.ScanRequest\x1a\x15.sink.v1.ScanResponseB-Z+github.com/liran/sink-go/api/sink/v1;sinkv1b\x06proto3"

var (
	file_sink_sink_proto_rawDescOnce sync.Once
	file_sink_sink_proto_rawDescData []byte
)

func file_sink_sink_proto_rawDescGZIP() []byte {
	file_sink_sink_proto_rawDescOnce.Do(func() {
		file_sink_sink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sink_sink_proto_rawDesc), len(file_sink_sink_proto_rawDesc)))
	})
	return file_sink_sink_proto_rawDescData
}

var file_sink_sink_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_sink_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_sink_sink_proto_goTypes = []any{
	(DocumentEncoding)(0),   // 0: sink.v1.DocumentEncoding
	(CompletionMode)(0),     // 1: sink.v1.CompletionMode
	(ReadStatus)(0),         // 2: sink.v1.ReadStatus
	(WriteMode)(0),          // 3: sink.v1.WriteMode
	(WriteStatus)(0),        // 4: sink.v1.WriteStatus
	(DeleteStatus)(0),       // 5: sink.v1.DeleteStatus
	(FailureCode)(0),        // 6: sink.v1.FailureCode
	(*RecordAddress)(nil),   // 7: sink.v1.RecordAddress
	(*RecordKey)(nil),       // 8: sink.v1.RecordKey
	(*OpaqueValue)(nil),     // 9: sink.v1.OpaqueValue
	(*Document)(nil),        // 10: sink.v1.Document
	(*RevisionToken)(nil),   // 11: sink.v1.RevisionToken
	(*ReadRequest)(nil),     // 12: sink.v1.ReadRequest
	(*ReadOperation)(nil),   // 13: sink.v1.ReadOperation
	(*ReadResponse)(nil),    // 14: sink.v1.ReadResponse
	(*ReadResult)(nil),      // 15: sink.v1.ReadResult
	(*WriteRequest)(nil),    // 16: sink.v1.WriteRequest
	(*WriteOperation)(nil),  // 17: sink.v1.WriteOperation
	(*PutOperation)(nil),    // 18: sink.v1.PutOperation
	(*MergeOperation)(nil),  // 19: sink.v1.MergeOperation
	(*LuaProgram)(nil),      // 20: sink.v1.LuaProgram
	(*WriteResponse)(nil),   // 21: sink.v1.WriteResponse
	(*WriteResult)(nil),     // 22: sink.v1.WriteResult
	(*DeleteRequest)(nil),   // 23: sink.v1.DeleteRequest
	(*DeleteOperation)(nil), // 24: sink.v1.DeleteOperation
	(*DeleteResponse)(nil),  // 25: sink.v1.DeleteResponse
	(*DeleteResult)(nil),    // 26: sink.v1.DeleteResult
	(*Failure)(nil),         // 27: sink.v1.Failure
	(*Command)(nil),         // 28: sink.v1.Command
	(*Header)(nil),          // 29: sink.v1.Header
	(*ExecuteRequest)(nil),  // 30: sink.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 31: sink.v1.ExecuteResponse
	(*QueryRequest)(nil),    // 32: sink.v1.QueryRequest
	(*SortField)(nil),       // 33: sink.v1.SortField
	(*Projection)(nil),      // 34: sink.v1.Projection
	(*QueryResponse)(nil),   // 35: sink.v1.QueryResponse
	(*CountRequest)(nil),    // 36: sink.v1.CountRequest
	(*CountResponse)(nil),   // 37: sink.v1.CountResponse
	(*ScanRequest)(nil),     // 38: sink.v1.ScanRequest
	(*ScanResponse)(nil),    // 39: sink.v1.ScanResponse
}
var file_sink_sink_proto_depIdxs = []int32{
	8,  // 0: sink.v1.RecordAddress.key:type_name -> sink.v1.RecordKey
	9,  // 1: sink.v1.RecordKey.opaque_value:type_name -> sink.v1.OpaqueValue
	0,  // 2: sink.v1.Document.encoding:type_name -> sink.v1.DocumentEncoding
	13, // 3: sink.v1.ReadRequest.operations:type_name -> sink.v1.ReadOperation
	7,  // 4: sink.v1.ReadOperation.address:type_name -> sink.v1.RecordAddress
	15, // 5: sink.v1.ReadResponse.results:type_name -> sink.v1.ReadResult
	2,  // 6: sink.v1.ReadResult.status:type_name -> sink.v1.ReadStatus
	10, // 7: sink.v1.ReadResult.document:type_name -> sink.v1.Document
	11, // 8: sink.v1.ReadResult.revision:type_name -> sink.v1.RevisionToken
	27, // 9: sink.v1.ReadResult.failure:type_name -> sink.v1.Failure
	1,  // 10: sink.v1.WriteRequest.completion_mode:type_name -> sink.v1.CompletionMode
	17, // 11: sink.v1.WriteRequest.operations:type_name -> sink.v1.WriteOperation
	20, // 12: sink.v1.WriteRequest.lua_programs:type_name -> sink.v1.LuaProgram
	7,  // 13: sink.v1.WriteOperation.address:type_name -> sink.v1.RecordAddress
	18, // 14: sink.v1.WriteOperation.put:type_name -> sink.v1.PutOperation
	19, // 15: sink.v1.WriteOperation.merge:type_name -> sink.v1.MergeOperation
	10, // 16: sink.v1.PutOperation.document:type_name -> sink.v1.Document
	3,  // 17: sink.v1.PutOperation.mode:type_name -> sink.v1.WriteMode
	10, // 18: sink.v1.MergeOperation.incoming_document:type_name -> sink.v1.Document
	20, // 19: sink.v1.MergeOperation.lua_program:type_name -> sink.v1.LuaProgram
	22, // 20: sink.v1.WriteResponse.results:type_name -> sink.v1.WriteResult
	4,  // 21: sink.v1.WriteResult.status:type_name -> sink.v1.WriteStatus
	11, // 22: sink.v1.WriteResult.revision:type_name -> sink.v1.RevisionToken
	27, // 23: sink.v1.WriteResult.failure:type_name -> sink.v1.Failure
	10, // 24: sink.v1.WriteResult.document:type_name -> sink.v1.Document
	1,  // 25: sink.v1.DeleteRequest.completion_mode:type_name -> sink.v1.CompletionMode
	24, // 26: sink.v1.DeleteRequest.operations:type_name -> sink.v1.DeleteOperation
	7,  // 27: sink.v1.DeleteOperation.address:type_name -> sink.v1.RecordAddress
	26, // 28: sink.v1.DeleteResponse.results:type_name -> sink.v1.DeleteResult
	5,  // 29: sink.v1.DeleteResult.status:type_name -> sink.v1.DeleteStatus
	27, // 30: sink.v1.DeleteResult.failure:type_name -> sink.v1.Failure
	6,  // 31: sink.v1.Failure.code:type_name -> sink.v1.FailureCode
	29, // 32: sink.v1.Command.headers:type_name -> sink.v1.Header
	28, // 33: sink.v1.ExecuteRequest.command:type_name -> sink.v1.Command
	29, // 34: sink.v1.ExecuteResponse.headers:type_name -> sink.v1.Header
	28, // 35: sink.v1.QueryRequest.command:type_name -> sink.v1.Command
	33, // 36: sink.v1.QueryRequest.sort:type_name -> sink.v1.SortField
	34, // 37: sink.v1.QueryRequest.projection:type_name -> sink.v1.Projection
	10, // 38: sink.v1.QueryResponse.documents:type_name -> sink.v1.Document
	28, // 39: sink.v1.CountRequest.command:type_name -> sink.v1.Command
	28, // 40: sink.v1.ScanRequest.command:type_name -> sink.v1.Command
	10, // 41: sink.v1.ScanResponse.documents:type_name -> sink.v1.Document
	12, // 42: sink.v1.Sink.Read:input_type -> sink.v1.ReadRequest
	16, // 43: sink.v1.Sink.Write:input_type -> sink.v1.WriteRequest
	23, // 44: sink.v1.Sink.Delete:input_type -> sink.v1.DeleteRequest
	30, // 45: sink.v1.Sink.Execute:input_type -> sink.v1.ExecuteRequest
	32, // 46: sink.v1.Sink.Query:input_type -> sink.v1.QueryRequest
	36, // 47: sink.v1.Sink.Count:input_type -> sink.v1.CountRequest
	38, // 48: sink.v1.Sink.Scan:input_type -> sink.v1.ScanRequest
	14, // 49: sink.v1.Sink.Read:output_type -> sink.v1.ReadResponse
	21, // 50: sink.v1.Sink.Write:output_type -> sink.v1.WriteResponse
	25, // 51: sink.v1.Sink.Delete:output_type -> sink.v1.DeleteResponse
	31, // 52: sink.v1.Sink.Execute:output_type -> sink.v1.ExecuteResponse
	35, // 53: sink.v1.Sink.Query:output_type -> sink.v1.QueryResponse
	37, // 54: sink.v1.Sink.Count:output_type -> sink.v1.CountResponse
	39, // 55: sink.v1.Sink.Scan:output_type -> sink.v1.ScanResponse
	49, // [49:56] is the sub-list for method output_type
	42, // [42:49] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_sink_sink_proto_init() }
func file_sink_sink_proto_init() {
	if File_sink_sink_proto != nil {
		return
	}
	file_sink_sink_proto_msgTypes[1].OneofWrappers = []any{
		(*RecordKey_StringValue)(nil),
		(*RecordKey_Int64Value)(nil),
		(*RecordKey_BytesValue)(nil),
		(*RecordKey_OpaqueValue)(nil),
	}
	file_sink_sink_proto_msgTypes[10].OneofWrappers = []any{
		(*WriteOperation_Put)(nil),
		(*WriteOperation_Merge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sink_sink_proto_rawDesc), len(file_sink_sink_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sink_sink_proto_goTypes,
		DependencyIndexes: file_sink_sink_proto_depIdxs,
		EnumInfos:         file_sink_sink_proto_enumTypes,
		MessageInfos:      file_sink_sink_proto_msgTypes,
	}.Build()
	File_sink_sink_proto = out.File
	file_sink_sink_proto_goTypes = nil
	file_sink_sink_proto_depIdxs = nil
}
